export const collection = [
  { title: "Cyber Human #1", img: "1.png" },
  { title: "Cyber Human #2", img: "2.png" },
  { title: "Cyber Human #3", img: "3.png" },
  { title: "Cyber Human #4", img: "4.png" },
  { title: "Cyber Human #5", img: "5.png" },
  { title: "Cyber Human #6", img: "6.png" },
  { title: "Cyber Human #7", img: "7.png" },
  { title: "Cyber Human #8", img: "8.png" },
  { title: "Cyber Human #9", img: "9.png" },
  { title: "Cyber Human #10", img: "10.png" },
  { title: "Cyber Human #11", img: "11.png" },
  { title: "Cyber Human #12", img: "12.png" },
  { title: "Cyber Human #13", img: "13.png" },
  { title: "Cyber Human #14", img: "14.png" },
  { title: "Cyber Human #15", img: "15.png" },
  { title: "Cyber Human #16", img: "16.png" },
  { title: "Cyber Human #17", img: "17.png" },
  { title: "Cyber Human #18", img: "18.png" },
  { title: "Cyber Human #19", img: "19.png" },
  { title: "Cyber Human #20", img: "20.png" },
  { title: "Cyber Human #21", img: "21.png" },
  { title: "Cyber Human #22", img: "22.png" },
  { title: "Cyber Human #23", img: "23.png" },
  { title: "Cyber Human #24", img: "24.png" },
  { title: "Cyber Human #25", img: "25.png" },
];
